export const examplePrompts = {
    "EN":
    {
        0: 'Create a piece of music inspired by the feeling of walking through a bustling city at night.',
        1: 'Imagine a journey through space and compose the soundtrack for it.',
        2: 'Reflect the beauty of autumn leaves cascading in the wind through a gentle and melancholic melody.',
        3: 'Imagine a carnival atmosphere and compose a lively, energetic tune for it.',
        4: 'Create a song inspired by the rhythm of ocean waves crashing against the shore.',
        5: 'Compose a lullaby that soothes the listener into a peaceful sleep.',
        6: 'Express the joy of reunion with loved ones through an uplifting and heartwarming composition.',
        7: 'Capture the essence of a cozy evening by the fireplace with a comforting musical composition.',
        8: 'Create a musical interpretation of a favorite childhood memory.',
        9: 'Compose a song that captures the essence of a thunderstorm rolling in.',
        10: 'Craft a piece of music that represents the cycle of seasons transitioning from winter to spring.',
        11: 'Imagine the soundtrack for an epic adventure movie and compose a heroic theme.',
        12: 'Imagine a serene sunrise and compose a melody that captures its beauty.',
        13: 'Craft a melody that mirrors the ebb and flow of a calm, moonlit ocean.',
        14: 'Reflect the excitement and anticipation of embarking on a grand adventure through your music.',
        15: 'Translate the energy of a bustling street market into a dynamic musical piece.',
        16: 'Craft a melody that embodies the bittersweet feeling of watching a sunset, knowing the day must end.',
        17: 'Dive into the rich tapestry of human history and compose a piece that reflects a specific era or event.',
        18: 'Convey the essence of freedom and liberation through a soaring and triumphant musical composition.',
        19: 'Express the chaos and excitement of a carnival atmosphere through a lively and energetic musical piece.',
        20: 'Translate the beauty and grace of a ballet performance into a delicate and enchanting melody.',
        21: 'Create a musical portrait of a beloved pet, capturing their personality and spirit in sound.',
        22: 'Dive into the depths of imagination and compose a whimsical melody inspired by fantastical creatures.',
        23: 'Craft a melody that reflects the gentle rhythm of a rain shower, soothing and meditative.',
        24: 'Craft a melody that reflects the emotions of nostalgia and longing.',
        25: 'Generate a piece of music that reflects the mood of a tranquil forest.',
        26: 'Craft a melody that expresses the joy of discovery and exploration.',
        27: 'Paint a vivid sonic landscape inspired by the vibrant colors and bustling activity of a city square.',
        28: 'Craft a musical narrative that tells the story of a hero\'s journey, complete with triumphs and setbacks.',
        29: 'Express the thrill of discovery and exploration through a dynamic and adventurous musical arrangement.',
        30: 'Reflect the passage of time through your music, from the fleeting moments of youth to the wisdom of age.',
        31: 'Create a piece of music inspired by a specific color, such as blue or red.',
        32: 'Compose a song that embodies the feeling of triumph over adversity.',
        33: 'Express the sensation of floating weightlessly through the cosmos in musical form.',
        34: 'Convey the feeling of nostalgia for simpler times through a heartfelt musical arrangement.',
        35: 'Explore the intricate beauty of a blooming garden through your composition.',
        36: 'Evoke the serenity of a misty morning in the mountains through your melodic expression.',
        37: 'Create a musical journey that mirrors the ups and downs of overcoming a significant challenge.',
        38: 'Explore the concept of timelessness through your music, capturing a sense of eternity in sound.',
        39: 'Dive into the realm of dreams and compose a piece that captures the surreal and ethereal nature of sleep.',
        40: 'Create a musical ode to the wonders of the natural world, celebrating its diversity and majesty.',
        41: 'Explore the concept of duality through your music, juxtaposing contrasting themes and motifs.',
        42: 'Dive into the realm of mythology and compose a piece inspired by ancient legends and folklore.',
        43: 'Explore the complexities of human emotions through your music, from sorrow to elation and everything in between.',
        44: 'Capture the essence of a thunderstorm rolling in, from the distant rumble to the crashing crescendo.'
    },
    "KR":
    {
        0: '야간에 번화 한 도시를 걷는 느낌에 영감을 받아 음악을 만들어줘.',
        1: '우주를 여행하는 것을 상상하고 그에 대한 사운드 트랙을 만들어줘.',
        2: '가을 낙엽이 바람에 흩날리는 아름다움을 부드럽고 우울한 멜로디로 만들어줘.',
        3: '축제 분위기를 상상하고 활기찬, 에너지 넘치는 곡을 작곡해줘.',
        4: '해변에 파도가 치는 리듬에서 영감을 받아 노래를 만들어줘.',
        5: '들은 이를 평화로운 잠으로 안정시키는 자장가를 작곡해줘.',
        6: '사랑하는 사람들과의 재회의 기쁨을 격려하고 따뜻한 작품을 통해 표현해줘.',
        7: '편안한 악상을 통해 벽난로 앞의 아늑한 저녁 분위기를 표현해줘.',
        8: '좋아하는 어린 시절의 기억을 음악적으로 해석해줘.',
        9: '번개가 몰려오는 것의 본질을 잡아낸 노래를 작곡해줘.',
        10: '겨울에서 봄으로 계절이 전환되는 과정을 대변하는 곡 구성을 만들어줘.',
        11: '대서사시 영화의 사운드 트랙을 상상하고 영웅적인 주제를 작곡해줘.',
        12: '고요한 일출을 상상하고 그 아름다움을 잡아내는 멜로디를 작곡해줘.',
        13: '차분하고 달빛이 비치는 바다의 파도가 빠르게 변하는 모습을 반영하는 곡을 만들어줘.',
        14: '큰 모험에 참여하는 것으로부터의 흥분과 기대감을 음악을 통해 반영해줘.',
        15: '번화 한 시장의 에너지를 다이내믹한 음악 작품으로 해석해줘.',
        16: '해가 지는 것을 보며 날이 끝날 것을 알게되는 씁쓸한 느낌을 음악으로 묘사해줘.',
        17: '특정 시대 또는 사건을 반영하는 음악 작품을 만들어줘.',
        18: '고난과 역경을 통해 자유와 해방의 본질을 상향하는 음악 작품을 작곡해줘.',
        19: '활기찬 카니발 분위기의 본질을 생동감 넘치는 음악 조각으로 표현해줘.',
        20: '발레 공연의 아름다움과 우아함을 섬세하고 매혹적인 멜로디로 만들어줘.',
        21: '소중한 애완 동물의 음악적인 초상화를 만들어 그들의 성격과 영혼을 소리로 표현해줘.',
        22: '환상적인 생물에 영감을 받은 신비한 멜로디를 작곡해줘.',
        23: '비 내리는 소리의 부드러운 리듬을 반영하는 곡을 만들어내줘.',
        24: '그리움과 갈망의 감정을 반영하는 멜로디를 만들어내줘.',
        25: '고요한 숲의 분위기를 반영하는 음악 조각을 생성해줘.',
        26: '발견과 탐험의 기쁨을 표현하는 음악적인 멜로디를 작성해줘.',
        27: '도심 광장의 생동감 넘치고 활기찬 활동에서 영감을 받은 생생한 소리 풍경을 그려보내줘.',
        28: '영웅의 여정을 이야기하는 음악적 서술을 만들어내줘. 성공과 실패를 모두 담아줘.',
        29: '중요한 도전을 극복하는 과정의 전체적인 구조를 반영하는 음악적 여정을 만들어내줘.',
        30: '음악을 통해 시간의 흐름을 반영해줘. 청춘의 순간부터 나이의 지혜까지.',
        31: '파란색 또는 빨강과 같은 특정 색상을 기반으로 한 곡을 작곡해줘.',
        32: '어려움을 이기는 성공의 느낌을 대변하는 노래를 만들어내줘.',
        33: '음악 형태로 우주 공간을 무게 없이 떠다니는 느낌을 표현해줘.',
        34: '과거의 간단한 시절에 대한 향수를 진심 어린 음악 편곡으로 표현해줘.',
        35: '음악의 언어를 통해 화려한 정원의 정교한 아름다움을 탐미해봐.',
        36: '산의 안개 가득한 아침의 평온을 멜로디적 표현을 통해 불러내줘.',
        37: '중요한 도전을 극복하는 과정의 고저를 반영하는 음악적 여정을 만들어내줘.',
        38: '음악을 통해 시간이 멈춘 것처럼 느껴지는 무한함의 개념을 탐구해줘.',
        39: '꿈의 세계로 들어가 수면의 비현실적이고 무의식적인 본질을 표현하는 곡을 작곡해줘.',
        40: '자연 세계의 경이로움과 웅장함에 대한 음악적 찬가를 만들어내줘.',
        41: '음악을 통해 이중성의 개념을 탐구해줘. 대조되는 주제와 모티프를 겹쳐놓아줘.',
        42: '신화의 영역으로 들어가고 고대 전설과 민간 이야기에서 영감을 받은 곡을 작곡해줘.',
        43: '음악을 통해 인간 감정의 복잡성을 탐색해줘. 슬픔부터 기쁨까지 다양한 감정을 다루어줘.',
        44: '멀리서 들리는 울음소리에서부터 번개가 치는 크레센도까지 번개가 치는 본질을 잡아내는 곡을 만들어내줘.'
    }
}