export const examplePrompts =
{
    0: 'Create a piece of music inspired by the feeling of walking through a bustling city at night.',
    1: 'Imagine a journey through space and compose the soundtrack for it.',
    2: 'Reflect the beauty of autumn leaves cascading in the wind through a gentle and melancholic melody.',
    3: 'Imagine a carnival atmosphere and compose a lively, energetic tune for it.',
    4: 'Create a song inspired by the rhythm of ocean waves crashing against the shore.',
    5: 'Compose a lullaby that soothes the listener into a peaceful sleep.',
    6: 'Express the joy of reunion with loved ones through an uplifting and heartwarming composition.',
    7: 'Capture the essence of a cozy evening by the fireplace with a comforting musical composition.',
    8: 'Create a musical interpretation of a favorite childhood memory.',
    9: 'Compose a song that captures the essence of a thunderstorm rolling in.',
    10: 'Craft a piece of music that represents the cycle of seasons transitioning from winter to spring.',
    11: 'Imagine the soundtrack for an epic adventure movie and compose a heroic theme.',
    12: 'Imagine a serene sunrise and compose a melody that captures its beauty.',
    13: 'Craft a melody that mirrors the ebb and flow of a calm, moonlit ocean.',
    14: 'Reflect the excitement and anticipation of embarking on a grand adventure through your music.',
    15: 'Translate the energy of a bustling street market into a dynamic musical piece.',
    16: 'Craft a melody that embodies the bittersweet feeling of watching a sunset, knowing the day must end.',
    17: 'Dive into the rich tapestry of human history and compose a piece that reflects a specific era or event.',
    18: 'Convey the essence of freedom and liberation through a soaring and triumphant musical composition.',
    19: 'Express the chaos and excitement of a carnival atmosphere through a lively and energetic musical piece.',
    20: 'Translate the beauty and grace of a ballet performance into a delicate and enchanting melody.',
    21: 'Create a musical portrait of a beloved pet, capturing their personality and spirit in sound.',
    22: 'Dive into the depths of imagination and compose a whimsical melody inspired by fantastical creatures.',
    23: 'Craft a melody that reflects the gentle rhythm of a rain shower, soothing and meditative.',
    24: 'Craft a melody that reflects the emotions of nostalgia and longing.',
    25: 'Generate a piece of music that reflects the mood of a tranquil forest.',
    26: 'Craft a melody that expresses the joy of discovery and exploration.',
    27: 'Paint a vivid sonic landscape inspired by the vibrant colors and bustling activity of a city square.',
    28: 'Craft a musical narrative that tells the story of a hero\'s journey, complete with triumphs and setbacks.',
    29: 'Express the thrill of discovery and exploration through a dynamic and adventurous musical arrangement.',
    30: 'Reflect the passage of time through your music, from the fleeting moments of youth to the wisdom of age.',
    31: 'Create a piece of music inspired by a specific color, such as blue or red.',
    32: 'Compose a song that embodies the feeling of triumph over adversity.',
    33: 'Express the sensation of floating weightlessly through the cosmos in musical form.',
    34: 'Convey the feeling of nostalgia for simpler times through a heartfelt musical arrangement.',
    35: 'Explore the intricate beauty of a blooming garden through your composition.',
    36: 'Evoke the serenity of a misty morning in the mountains through your melodic expression.',
    37: 'Create a musical journey that mirrors the ups and downs of overcoming a significant challenge.',
    38: 'Explore the concept of timelessness through your music, capturing a sense of eternity in sound.',
    39: 'Dive into the realm of dreams and compose a piece that captures the surreal and ethereal nature of sleep.',
    40: 'Create a musical ode to the wonders of the natural world, celebrating its diversity and majesty.',
    41: 'Explore the concept of duality through your music, juxtaposing contrasting themes and motifs.',
    42: 'Dive into the realm of mythology and compose a piece inspired by ancient legends and folklore.',
    43: 'Explore the complexities of human emotions through your music, from sorrow to elation and everything in between.',
    44: 'Capture the essence of a thunderstorm rolling in, from the distant rumble to the crashing crescendo.'
}